# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x05proto\"\x82\x01\n\x0e\x44ictionaryData\x12-\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1f.proto.DictionaryData.DataEntry\x12\x14\n\x0cuniversal_id\x18\x02 \x01(\x05\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\".\n\x08TextData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x14\n\x0cuniversal_id\x18\x02 \x01(\x05\"0\n\nSpeechData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x14\n\x0cuniversal_id\x18\x02 \x01(\x05\"=\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cuniversal_id\x18\x03 \x01(\x05\x32\x42\n\x07ModuleB\x12\x37\n\x12\x65ventToTextRequest\x12\x15.proto.DictionaryData\x1a\n.proto.Ack2=\n\x07ModuleC\x12\x32\n\x13textToSpeechRequest\x12\x0f.proto.TextData\x1a\n.proto.Ack2B\n\x07ModuleD\x12\x37\n\x16ReproduceSpeechRequest\x12\x11.proto.SpeechData\x1a\n.proto.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DICTIONARYDATA_DATAENTRY']._loaded_options = None
  _globals['_DICTIONARYDATA_DATAENTRY']._serialized_options = b'8\001'
  _globals['_DICTIONARYDATA']._serialized_start=22
  _globals['_DICTIONARYDATA']._serialized_end=152
  _globals['_DICTIONARYDATA_DATAENTRY']._serialized_start=109
  _globals['_DICTIONARYDATA_DATAENTRY']._serialized_end=152
  _globals['_TEXTDATA']._serialized_start=154
  _globals['_TEXTDATA']._serialized_end=200
  _globals['_SPEECHDATA']._serialized_start=202
  _globals['_SPEECHDATA']._serialized_end=250
  _globals['_ACK']._serialized_start=252
  _globals['_ACK']._serialized_end=313
  _globals['_MODULEB']._serialized_start=315
  _globals['_MODULEB']._serialized_end=381
  _globals['_MODULEC']._serialized_start=383
  _globals['_MODULEC']._serialized_end=444
  _globals['_MODULED']._serialized_start=446
  _globals['_MODULED']._serialized_end=512
# @@protoc_insertion_point(module_scope)
