# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x05proto\"l\n\x0e\x44ictionaryData\x12-\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1f.proto.DictionaryData.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1a\n\nStringData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t24\n\x07ModuleA\x12)\n\x06Notify\x12\x11.proto.StringData\x1a\x0c.proto.Empty2<\n\x07ModuleB\x12\x31\n\x0cProcessFromA\x12\x15.proto.DictionaryData\x1a\n.proto.Ack24\n\x07ModuleC\x12)\n\x08\x46inalize\x12\x11.proto.StringData\x1a\n.proto.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DICTIONARYDATA_DATAENTRY']._loaded_options = None
  _globals['_DICTIONARYDATA_DATAENTRY']._serialized_options = b'8\001'
  _globals['_DICTIONARYDATA']._serialized_start=21
  _globals['_DICTIONARYDATA']._serialized_end=129
  _globals['_DICTIONARYDATA_DATAENTRY']._serialized_start=86
  _globals['_DICTIONARYDATA_DATAENTRY']._serialized_end=129
  _globals['_STRINGDATA']._serialized_start=131
  _globals['_STRINGDATA']._serialized_end=157
  _globals['_EMPTY']._serialized_start=159
  _globals['_EMPTY']._serialized_end=166
  _globals['_ACK']._serialized_start=168
  _globals['_ACK']._serialized_end=207
  _globals['_MODULEA']._serialized_start=209
  _globals['_MODULEA']._serialized_end=261
  _globals['_MODULEB']._serialized_start=263
  _globals['_MODULEB']._serialized_end=323
  _globals['_MODULEC']._serialized_start=325
  _globals['_MODULEC']._serialized_end=377
# @@protoc_insertion_point(module_scope)
