# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.data_pb2 as data__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModuleAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Notify = channel.unary_unary(
                '/proto.ModuleA/Notify',
                request_serializer=data__pb2.StringData.SerializeToString,
                response_deserializer=data__pb2.Empty.FromString,
                _registered_method=True)


class ModuleAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Notify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=data__pb2.StringData.FromString,
                    response_serializer=data__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ModuleA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ModuleA', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModuleA/Notify',
            data__pb2.StringData.SerializeToString,
            data__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModuleBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFromA = channel.unary_unary(
                '/proto.ModuleB/ProcessFromA',
                request_serializer=data__pb2.DictionaryData.SerializeToString,
                response_deserializer=data__pb2.Ack.FromString,
                _registered_method=True)


class ModuleBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessFromA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFromA': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFromA,
                    request_deserializer=data__pb2.DictionaryData.FromString,
                    response_serializer=data__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ModuleB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ModuleB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessFromA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModuleB/ProcessFromA',
            data__pb2.DictionaryData.SerializeToString,
            data__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModuleCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Finalize = channel.unary_unary(
                '/proto.ModuleC/Finalize',
                request_serializer=data__pb2.StringData.SerializeToString,
                response_deserializer=data__pb2.Ack.FromString,
                _registered_method=True)


class ModuleCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Finalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Finalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalize,
                    request_deserializer=data__pb2.StringData.FromString,
                    response_serializer=data__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ModuleC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ModuleC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Finalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModuleC/Finalize',
            data__pb2.StringData.SerializeToString,
            data__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
