# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.data_pb2 as data__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModuleBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.eventToTextRequest = channel.unary_unary(
                '/proto.ModuleB/eventToTextRequest',
                request_serializer=data__pb2.DictionaryData.SerializeToString,
                response_deserializer=data__pb2.Ack.FromString,
                _registered_method=True)


class ModuleBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def eventToTextRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'eventToTextRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.eventToTextRequest,
                    request_deserializer=data__pb2.DictionaryData.FromString,
                    response_serializer=data__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ModuleB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ModuleB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def eventToTextRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModuleB/eventToTextRequest',
            data__pb2.DictionaryData.SerializeToString,
            data__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModuleCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.textToSpeechRequest = channel.unary_unary(
                '/proto.ModuleC/textToSpeechRequest',
                request_serializer=data__pb2.TextData.SerializeToString,
                response_deserializer=data__pb2.Ack.FromString,
                _registered_method=True)


class ModuleCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def textToSpeechRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'textToSpeechRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.textToSpeechRequest,
                    request_deserializer=data__pb2.TextData.FromString,
                    response_serializer=data__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ModuleC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ModuleC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def textToSpeechRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModuleC/textToSpeechRequest',
            data__pb2.TextData.SerializeToString,
            data__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModuleDStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReproduceSpeechRequest = channel.unary_unary(
                '/proto.ModuleD/ReproduceSpeechRequest',
                request_serializer=data__pb2.SpeechData.SerializeToString,
                response_deserializer=data__pb2.Ack.FromString,
                _registered_method=True)


class ModuleDServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReproduceSpeechRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleDServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReproduceSpeechRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ReproduceSpeechRequest,
                    request_deserializer=data__pb2.SpeechData.FromString,
                    response_serializer=data__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ModuleD', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ModuleD', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleD(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReproduceSpeechRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModuleD/ReproduceSpeechRequest',
            data__pb2.SpeechData.SerializeToString,
            data__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
